### Get all cats
GET http://localhost:3000/api/v1/cats

### Get one cat
GET http://localhost:3000/api/v1/cats/1

### Add a new cat
POST http://localhost:3000/api/v1/cats
content-type: application/json

{
  "cat_name": "Testikissa",
  "weight": 3.2,
  "owner": "Mikko",
  "birthdate": "2023-01-01"
}

### Update a cat
PUT http://localhost:3000/api/v1/cats/1
content-type: application/json

{
  "cat_name": "Updated name"
}

### Delete a cat
DELETE http://localhost:3000/api/v1/cats/1

### Get all users
GET http://localhost:3000/api/v1/users

### Get one user
GET http://localhost:3000/api/v1/users/1

### Add a new user
POST http://localhost:3000/api/v1/users
content-type: application/json

{
  "name": "Test User",
  "username": "testuser",
  "email": "test@example.com",
  "role": "user",
  "password": "test1234"
}

### Update a user
PUT http://localhost:3000/api/v1/users/1
content-type: application/json

{
  "name": "Updated name"
}

### Delete a user
DELETE http://localhost:3000/api/v1/users/1

### Add a new cat with an image
POST http://localhost:3000/api/v1/cats HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="cat_name"

Testikissa
--MyBoundary
Content-Disposition: form-data; name="weight"

3.2
--MyBoundary
Content-Disposition: form-data; name="owner"

Mikko
--MyBoundary
Content-Disposition: form-data; name="birthdate"

2023-10-08
--MyBoundary
Content-Disposition: form-data; name="cat"; filename="cool_pancake_tp.png"
Content-Type: image/png

< ./public/cool_pancake_tp.png
--MyBoundary--

